spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    driver-class-name: ${hugo.datasource.driver-class-name}
    url: ${hugo.datasource.url}
    username: ${hugo.datasource.username}
    password: ${hugo.datasource.password}

  redis:
    host: ${hugo.redis.host}
    port: ${hugo.redis.port}
    database: ${hugo.redis.database}
    password: ${hugo.redis.password}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.hugo.entity

logging:
  level:
    com:
      hugo:
        mapper: debug
        service: info
        controller: info
    org.springframework.jdbc.support.JdbcTransactionManager: debug

hugo:
  jwt:
    # admin
    admin-secret-key: hugoAdmin
    admin-ttl: 7200000
    admin-token-name: token
    # user
    user-secret-key: hugoUser
    user-ttl: 7200000
    user-token-name: authentication

  alioss:
    endpoint: ${hugo.alioss.endpoint}
    access-key-id: ${hugo.alioss.access-key-id}
    access-key-secret: ${hugo.alioss.access-key-secret}
    bucket-name: ${hugo.alioss.bucket-name}

  wechat:
    appid: ${hugo.wechat.appid}
    secret: ${hugo.wechat.secret}
    mchid: ${hugo.wechat.mchid}
    mch-serial-no: ${hugo.wechat.mch-serial-no}
    private-key-file-path: ${hugo.wechat.private-key-file-path}
    api-v3-key: ${hugo.wechat.api-v3-key}
    we-chat-pay-cert-file-path: ${hugo.wechat.we-chat-pay-cert-file-path}
    notify-url: ${hugo.wechat.notify-url}
    refund-notify-url:  ${hugo.wechat.refund-notify-url}

  shop:
    address: ${hugo.shop.address}

  baidu:
    ak: ${hugo.baidu.ak}